apiVersion: v1
kind: Service
metadata:
  name: artifact
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: artifact
spec:
  type: ClusterIP
  ports:
    - port: 10054
      targetPort: 10054
      protocol: TCP
      name: http
    - port: 50054
      targetPort: 50054
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: artifact