apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-pipeline
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xcoding
      app.kubernetes.io/instance: xcoding
      app.kubernetes.io/component: ci-pipeline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xcoding
        app.kubernetes.io/instance: xcoding
        app.kubernetes.io/component: ci-pipeline
    spec:
      enableServiceLinks: false
      containers:
      - name: ci-pipeline
        image: localhost:31500/ci-pipeline-service:tdcx6c0e
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 10055
          protocol: TCP
        env:
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: xcoding_ci
        - name: DB_SSLMODE
          value: disable
        - name: GRPC_ADDRESS
          value: 0.0.0.0
        - name: GRPC_PORT
          value: '50055'
        - name: HTTP_ADDRESS
          value: 0.0.0.0
        - name: HTTP_PORT
          value: '10055'
        - name: PROJECT_GRPC_ADDRESS
          value: project
        - name: PROJECT_GRPC_PORT
          value: '50052'
        - name: EXECUTOR_GRPC_ADDRESS
          value: ci-executor
        - name: EXECUTOR_GRPC_PORT
          value: '50056'
        - name: RABBITMQ_URL
          value: amqp://admin:admin123@rabbitmq:5672/
        - name: RABBITMQ_QUEUE
          value: ci_builds
        livenessProbe:
          grpc:
            port: 50055
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 50055
          initialDelaySeconds: 10
          periodSeconds: 10
