apiVersion: v1
kind: Service
metadata:
  name: ci-pipeline
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-pipeline
spec:
  type: ClusterIP
  ports:
    - port: 10055
      targetPort: 10055
      protocol: TCP
      name: http
    - port: 50055
      targetPort: 50055
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-pipeline