apiVersion: v1
kind: Service
metadata:
  name: project
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: project
spec:
  type: ClusterIP
  ports:
    - port: 10052
      targetPort: 10052
      protocol: TCP
      name: http
    - port: 50052
      targetPort: 50052
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: project