apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-executor-sa
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-executor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-executor-role
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-executor
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","get","list","watch","delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-executor-rolebinding
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-executor-role
subjects:
  - kind: ServiceAccount
    name: ci-executor-sa