apiVersion: v1
kind: Service
metadata:
  name: ci-executor
  labels:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-executor
spec:
  type: ClusterIP
  ports:
    - port: 10056
      targetPort: 10056
      protocol: TCP
      name: http
    - port: 50056
      targetPort: 50056
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: xcoding
    app.kubernetes.io/instance: xcoding
    app.kubernetes.io/component: ci-executor